WIP: snARS Integration
delvtech/hyperdrive pull request #1190
Opened 2024-10-14 19:33 UTC by jalextowle

# Description

TODO

2024-10-14 22:51 UTC, mcclurejt approved these changes
LGTM

2024-10-14 22:51 UTC, mcclurejt commented on deployments.json
> -        "ElementDAO ERC4626 Hyperdrive Deployer Coordinator_ERC4626HyperdriveCoreDeployer": {
are these going to get replaced?

2024-10-16 12:06 UTC, jrhea requested changes

2024-10-16 12:06 UTC, jrhea commented on tasks/deploy/config/base/snars-182day.ts
> +            positionDuration: parseDuration(SIX_MONTHS),
didn't we talk about this being 1 month or 3 months?

2024-10-16 12:06 UTC, jrhea commented on hardhat.config.base.ts
> +                    BASE_SNARS_182DAY,
if the term is going to be 1 month or 3 months we should rename this

2024-10-16 21:52 UTC, jrhea approved these changes

2024-10-18 20:03 UTC, jalextowle commented
Closed because these changes were incorporated into #1189

2024-10-21 23:13 UTC, closed without merging